### PR TITLE
Add rz decomposition routine

### PR DESCRIPTION
**Pull request by SmithB**
When solving large linear systems, it's nice to be able to use parts of a QR decomposition without forming the Q matrix.  Suitesparse allows a Q-less decomposition, which forms R and Z such that z=Q^Td.  The modifications I made to the code let PySPQR return Q and Z for sparse systems.

### CODE REVIEW

**Comment by yig** [comment]
I am trying to decide if I like the function name. I looked to MATLAB for inspiration, but they don't have a different name. They decide what to compute based on the output arguments.

Some alternatives:

* zr(), since z is returned first. e is never mentioned for some reason.

* a keyword argument to qr() to specify what should be returned (compute_Q = False)

**Comment by SmithB** [comment]
I'd be happy either way.  Thanks!

**Comment by yig** [comment]
Sorry about the delay. Can you clarify what R and z are? Is it the "[C,R,p] = qr(A,B,'vector')" version on this MATLAB page: https://www.mathworks.com/help/symbolic/qr.html

**Review by yig — APPROVED** [review]
Looks good to me.

**Pull request merged**
